		<div id="menu">
			<ul>
				<li><a href="<?= $this->url(array('controller' => 'accueil', 'action' => 'index'),'default', true) ?>">Accueil</a></li>
				<li><a href="<?= $this->url(array('controller' => 'administration', 'action' => 'index'),'default', true) ?>">Administration</a></li>
				<li><a href="<?= $this->url(array('controller' => 'album', 'action' => 'index'),'default', true) ?>">Album</a></li>
				<li><a href="<?= $this->url(array('controller' => 'annonce', 'action' => 'index'),'default', true) ?>">Annonce</a></li>
				<li><a href="<?= $this->url(array('controller' => 'aps', 'action' => 'index'),'default', true) ?>">APS</a></li>
				<li><a href="<?= $this->url(array('controller' => 'calendrier', 'action' => 'index'),'default', true) ?>">Calendrier</a></li>
				<li><a href="<?= $this->url(array('controller' => 'commune', 'action' => 'index'),'default', true) ?>">Commune</a></li>
				<li><a href="<?= $this->url(array('controller' => 'cmf', 'action' => 'index'),'default', true) ?>">Conseil Municipal</a></li>
				<li><a href="<?= $this->url(array('controller' => 'contact', 'action' => 'index'),'default', true) ?>">Contact</a></li>
				<li><a href="<?= $this->url(array('controller' => 'livredor', 'action' => 'index'),'default', true) ?>">Livre d'Or</a></li>
				<li><a href="<?= $this->url(array('controller' => 'lien', 'action' => 'index'),'default', true) ?>">Lien</a></li>
				<li><a href="<?= $this->url(array('controller' => 'news', 'action' => 'index'),'default', true) ?>">News</a></li>
				<li><a href="<?= $this->url(array('controller' => 'newsletter', 'action' => 'index'),'default', true) ?>">Newsletter</a></li>
				<li><a href="<?= $this->url(array('controller' => 'partenaire', 'action' => 'index'),'default', true) ?>">Partenaire</a></li>
				<li><a href="<?= $this->url(array('controller' => 'reunion', 'action' => 'index'),'default', true) ?>">Réunion</a></li>
				<li><a href="<?= $this->url(array('controller' => 'log', 'action' => 'index'),'default', true) ?>">Log Admin</a></li>
			</ul>
		</div>