		<div id="menu">
			<ul>
				<li><a href="<?= $this->url(array('controller' => 'accueil', 'action' => 'index'),'default', true) ?>">Accueil</a></li>
				<li><a href="<?= $this->url(array('controller' => 'staff', 'action' => 'index'),'default', true) ?>">Staff</a></li>
				<li><a href="<?= $this->url(array('controller' => 'lan', 'action' => 'index'),'default', true) ?>">Lan</a></li>
				<li><a href="<?= $this->url(array('controller' => 'charte', 'action' => 'index'),'default', true) ?>">Chartes</a></li>
				<li><a href="<?= $this->url(array('controller' => 'inscription', 'action' => 'index'),'default', true) ?>">Inscription</a></li>
				<li><a href="<?= $this->url(array('controller' => 'jeux', 'action' => 'index'),'default', true) ?>">Jeux</a></li>
				<li><a href="<?= $this->url(array('controller' => 'forum', 'action' => 'index'),'default', true) ?>">Forum</a></li>
				<li><a href="<?= $this->url(array('controller' => 'partenaire', 'action' => 'index'),'default', true) ?>">Partenaire</a></li>
				<li><a href="<?= $this->url(array('controller' => 'log', 'action' => 'index'),'default', true) ?>">Log Admin</a></li>
			</ul>
		</div>