<?= $this->doctype(); echo "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
	<head>  
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
		<title>LAG - Local Arena Games</title>
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/global.css" />
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/jquery/jquery.css" />
		<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery/jquery-1.3.2.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery/jquery-ui-1.7.2.custom.min.js"></script>
	</head> 
	<body>
		<div id="global">
			<div id="header">
				<div id="search">
					<form method="post" action="">
						<table border="0">
							<tr>
								<td valign="middle" width="24"><img src="<?php echo $this->baseUrl();?>/images/icones/icon-search.png" alt="Recherche" title="Recherche" /></td>
								<td width="60" valign="middle">Recherche</td>
								<td valign="middle"> : </td>
								<td valign="middle"> <input type="text" /> <input type="submit" value="ok" class="button" /></td>
							</tr>
						</table>
					</form>
				</div>
				<div id="menu">
					<?= utf8_encode($this->render('menu.phtml')) ?>
				</div>

				<div id="submenu">
					<?= utf8_encode($this->render('submenu.phtml')) ?>
				</div>
			</div>
			<div id="content">
				<?= $this->layout()->content ?>
			</div>
			<div id="footer">
			
			</div>
			<div id="footer-link">
				<?= utf8_encode($this->render('footer.phtml'))  ?>
			</div>
		</div>
	</body>
</html>
