	<ul>
		<li><a href="<?php echo $this->baseUrl();?>/plansite/">Plan du site</a> - </li>
		<li><a href="<?php echo $this->baseUrl();?>/mentionlegale/">Mentions l&eacute;gales</a> - </li>
		<li><a href="<?php echo $this->baseUrl();?>/bug/form">Signaler un bug</a> - </li>
		<li><a href="<?php echo $this->baseUrl();?>/contact/form">Nous contacter</a></li>
	</ul>
    <br />
    &copy; 2009-2010 Local Arena Games - Tous droits r&eacute;serv&eacute;s.